### ISSUE TITLE
Where do you input the result of the game?

### ISSUE THREAD

**Issue by bruce-ricard** [jlouis/o-glicko2#1]
I don't understand where you input the result of the game. The Glicko2 paper says that you have to enter 0, 1/2 or 1 for each game somewhere to calculate the new rating, but the "rate" function just takes a player and a list of opponents as argument. Am I misunderstanding something?

**Comment by bruce-ricard** [comment]
I think that I got it, the sj is the result of the game, isn't it?

**Comment by jlouis** [comment]
Indeed, `sj` is the outcome. Usually `0` is a loss, and `1` is a win whereas `0.5` is a draw (if your game allows for draws, that is). I.e., "player you are rating lost/won to that particular opponent".

The code implements the Glicko2 computation with one slight change. The volatility computation requires finding a root. In Glickman's original paper was a Newton-Rhapson. This can sometimes cycle, so he changed it to the Illinois method. The implementation here uses Ridders' method, which is often faster at root finding and also proved to be more numerically stable than the other methods when I ran on large data sets.

As for the speed, I also have Go and Erlang implementations. Go beats OCaml on native code with a factor of 2 on this. But that was before flambda and I believe this code is something flambda would love to optimize.

Also, this repository is quite short on a README file, which makes it harder to understand. I mostly implemented it for benchmarking, so I didn't bother writing down the README file (my computation eventually ended up being written in Go, because the SQL interfacing was a bit easier and the code contained no higher-order work).

**Comment by bruce-ricard** [comment]
Thanks for the reply. Makes sense. Another question: the paper talks about an update of the RD if a player doesn't play during a rating period, is one of the functions doing that?

**Comment by jlouis** [comment]
It is the (non-exported) phi_star function which does that. Scale down, run phi_star, scale up. From another project:

https://github.com/jlouis/qlglicko_core/blob/master/src/qlg_rank.erl#L147-L157

you will need the Sigma, i.e. the volatility, of the player as well. Perhaps it is the same as doing a ranking with the empty opponent set, but you can avoid some computation by detecting the case directly.
